# Generated by Django 6.0.6 on 2026-06-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Helpline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('women', 'Women Helpline'), ('police', 'Police'), ('medical', 'Medical'), ('child', 'Child Helpline'), ('mental', 'Mental Health'), ('legal', 'Legal Aid'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('available_24x7', models.BooleanField(default=True)),
                ('state', models.CharField(blank=True, help_text='Leave blank for national helpline', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
